### ISSUE TITLE
Sample build as yaml

### ISSUE THREAD

**Issue by jkanczler** [Dealogic/webpack-vsts-extension#85]
Could you provide a sample yaml build definition?

**Comment by jkanczler** [comment]
![image](https://user-images.githubusercontent.com/10925650/52264708-936cde80-2932-11e9-9858-20cb7bef14d5.png)

```
- phase: Frontend
  steps:
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: Install Yarn 1.5.1
    inputs:
      versionSpec: 1.5.1
  - task: gittools.gitversion.gitversion-task.GitVersion@3
    displayName: GitVersion
    inputs:
      updateAssemblyInfo: true
  - task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1
    displayName: Replace tokens
    inputs:
      filePattern: ./widget/version.ts
      tokenRegex: '__([\w\.]+)__'
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: 'Yarn: install dependency packages'
    inputs:
      ProjectDirectory: widget
      Arguments: install
  - task: Dealogic.webpack-vsts-extension.webpack.webpack@4
    displayName: Running Webpack
    inputs:
      webpackCliArguments: '--config ./webpack.dist.config.ts --display minimal'
      treatWarningsAs: errors
      workingFolder: widget
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: Run unit tests
    inputs:
      ProjectDirectory: widget
      Arguments: test
  - task: CopyFiles@2
    displayName: 'Copy $(GitVersion.SemVer) files to: $(Build.ArtifactStagingDirectory)/widget/$(GitVersion.SemVer)'
    inputs:
      SourceFolder: 'widget/dist/$(GitVersion.SemVer)'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/widget/$(GitVersion.SemVer)'
      CleanTargetFolder: true
      OverWrite: true
  - task: CopyFiles@2
    displayName: 'Copy $(GitVersion.Major)-LATEST files to: $(Build.ArtifactStagingDirectory)/widget/$(GitVersion.Major)-LATEST'
    inputs:
      SourceFolder: 'widget/dist/$(GitVersion.Major)-LATEST'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/widget/$(GitVersion.Major)-LATEST'
      CleanTargetFolder: true
      OverWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
      publishLocation: Container
```
